apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpp-app
  template:
    metadata:
      labels:
        app: cpp-app
    spec:
      containers:
        - name: cpp-container
          image: cppacr.azurecr.io/cppapp:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cpp-web-service
spec:
  type: ClusterIP
  selector:
    app: cpp-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cpp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: cppapp.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cpp-web-service
                port:
                  number: 80
